export const initialValues = {
  // Step 0 boarding
  voucher: "",

  // Step 1 Identitas Pemohon
  namaLengkapPemohon: "",
  niknit: "",
  kewarganegaraan: "Indonesia",
  kewarganegaraanAsing: "",
  jenisKelaminPemohon: "",
  statusPerkawinan: "",
  pekerjaanPemohon: "",
  tempatLahirPemohon: "",
  tanggalLahirPemohon: "",
  alasanPemohon: "Putusnya perkawinan",
  nomorAktaPemohon: "",
  tanggalAktaPemohon: "",
  tempatTinggalPemohon: "",
  negaraTinggalPemohon: "",
  nomorHandphonePemohon: "",
  nomorTeleponPemohon: "",
  provinsi: "",
  kabkot: "",
  emailPemohon: "",
  alamatTinggalPemohon: "",
  nomorAktaAnak: "",
  tanggalAktaAnak: "",
  nomorAktaPerkawinan: "",
  tanggalAktaPerkawinan: "",
  nomorAktaCerai: "",
  tanggalAktaCerai: "",
  nomorPasporRI: "",
  wilayahTerbitPasporRI: "",
  tanggalKedaluarsaPaspor: "",

  // Step 2 Identitas Suami / Istri / Anak
  namaLengkapPasangan: "",
  kewarganegaraanPasangan: "",
  emailPasangan: "",
  nomorHpPasangan: "",
  tempatLahirPasangan: "",
  tanggalLahirPasangan: "",
  alamatTinggalPasangan: "",
  namaLengkapAnak: "",
  emailAnak: "",
  tempatLahirAnak: "",
  tanggalLahirAnak: "",
  alamatTinggalAnak: "",

  // Step 3 Surat permohonan
  suratPermohonan: "",

  // Step 4 Unggah dokumen
  fotokopiAktaKelahiran: null,
  fotokopiPasporRI: null,
  fotokopiKtp: null,
  fotokopiAktaNikah: null,
  fotokopiAktaCerai: null,
  fotokopiAktaKelahiranAnak: null,
  suratPernyataanKesetiaan: null,
  suratPernyataanMelepaskan: null,
  daftarRiwayatHidup: null,
  pasFoto: null,
};
