// Provinsi
export const FETCH_PROVINSI_REQUEST = "FETCH_PROVINSI_REQUEST";
export const FETCH_PROVINSI_SUCCESS = "FETCH_PROVINSI_SUCCESS";
export const FETCH_PROVINSI_ERROR = "FETCH_PROVINSI_ERROR";

// Kota/Kabupaten
export const FETCH_KOTAKAB_REQUEST = "FETCH_KOTAKAB_REQUEST";
export const FETCH_KOTAKAB_REQUEST_BY_PROVINSI =
  "FETCH_KOTAKAB_REQUEST_BY_PROVINSI";
export const FETCH_KOTAKAB_SUCCESS = "FETCH_KOTAKAB_SUCCESS";
export const FETCH_KOTAKAB_ERROR = "FETCH_KOTAKAB_ERROR";

// Kecamatan
export const FETCH_KECAMATAN_REQUEST = "FETCH_KECAMATAN_REQUEST";
export const FETCH_KECAMATAN_REQUEST_BY_KOTAKAB =
  "FETCH_KECAMATAN_REQUEST_BY_KOTAKAB";
export const FETCH_KECAMATAN_SUCCESS = "FETCH_KECAMATAN_SUCCESS";
export const FETCH_KECAMATAN_ERROR = "FETCH_KECAMATAN_ERROR";

// Desa
export const FETCH_DESA_REQUEST = "FETCH_DESA_REQUEST";
export const FETCH_DESA_REQUEST_BY_KECAMATAN =
  "FETCH_DESA_REQUEST_BY_KECAMATAN";
export const FETCH_DESA_SUCCESS = "FETCH_DESA_SUCCESS";
export const FETCH_DESA_ERROR = "FETCH_DESA_ERROR";

// Negara
export const FETCH_NEGARA_REQUEST = "FETCH_NEGARA_REQUEST";
export const FETCH_NEGARA_SUCCESS = "FETCH_NEGARA_SUCCESS";
export const FETCH_NEGARA_ERROR = "FETCH_NEGARA_ERROR";

// Pekerjaan
export const FETCH_PEKERJAAN_REQUEST = "FETCH_PEKERJAAN_REQUEST";
export const FETCH_PEKERJAAN_SUCCESS = "FETCH_PEKERJAAN_SUCCESS";
export const FETCH_PEKERJAAN_ERROR = "FETCH_PEKERJAAN_ERROR";

// Agama
export const FETCH_AGAMA_REQUEST = "FETCH_AGAMA_REQUEST";
export const FETCH_AGAMA_SUCCESS = "FETCH_AGAMA_SUCCESS";
export const FETCH_AGAMA_ERROR = "FETCH_AGAMA_ERROR";

// Status Kawin
export const FETCH_STATUS_KAWIN_REQUEST = "FETCH_STATUS_KAWIN_REQUEST";
export const FETCH_STATUS_KAWIN_SUCCESS = "FETCH_STATUS_KAWIN_SUCCESS";
export const FETCH_STATUS_KAWIN_ERROR = "FETCH_STATUS_KAWIN_ERROR";

// masalah kota kabupaten pasangan yang nyangkut pake id provinsi pemohon
export const FETCH_KOTAKAB_REQUEST_PSGN = "FETCH_KOTAKAB_REQUEST_PSGN";
export const FETCH_KOTAKAB_REQUEST_BY_PROVINSI_PSGN =
  "FETCH_KOTAKAB_REQUEST_BY_PROVINSI_PSGN";
export const FETCH_KOTAKAB_SUCCESS_PSGN = "FETCH_KOTAKAB_SUCCESS_PSGN";
export const FETCH_KOTAKAB_ERROR_PSGN = "FETCH_KOTAKAB_ERROR_PSGN";
