export const initialValues = {
  // Step 0 - Voucher
  voucher: "",

  // Step 1 - Identitas Pemohon
  namaLengkapPemohon: "",
  jenisKelaminPemohon: "",
  nomorHandphonePemohon: "",
  nomorTeleponPemohon: "",
  tempatLahirPemohon: "",
  tanggalLahirPemohon: null,
  emailPemohon: "",
  pekerjaanPemohon: "",
  niknit: "",
  statusPerkawinan: "",
  kewarganegaraanAsing: "",
  tempatTglIndoPemohon: "",
  tempatTglLnPemohon: "",
  negaraPemohon: "",
  nmrAktaLahirPemohon: "",
  tAktaLahirPemohon: null,
  nmrAktaPerkawinanPemohon: "",
  tAktaPerkawinanPemohon: null,
  nmrPasporRI: "",
  wlyTerbitPasporRI: "",
  tglKedaluarsaPasporRi: null,
  nmrPasporAsing: "",
  wlyTerbitPasporAsing: "",
  tglKedaluarsaPasporAsing: null,

  // Step 2 - Identitas Ibu, Ayah, Pasangan
  namaLengkapIbu: "",
  kewarganegaraanIbu: "",
  emailIbu: "",
  nomorHpIbu: "",
  tempatLahirIbu: "",
  tanggalLahirIbu: null,
  alamatTinggalIbu: "",
  statusPerkawinanIbu: "",
  agamaIbu: "",

  namaLengkapAyah: "",
  kewarganegaraanAyah: "",
  emailAyah: "",
  nomorHpAyah: "",
  tempatLahirAyah: "",
  tanggalLahirAyah: null,
  alamatTinggalAyah: "",
  statusPerkawinanAyah: "",
  agamaAyah: "",

  namaLengkapPasangan: "",
  kewarganegaraanPasangan: "",
  emailPasangan: "",
  nomorHpPasangan: "",
  tempatLahirPasangan: "",
  tanggalLahirPasangan: null,
  alamatTinggalPasangan: "",
  statusPerkawinanPasangan: "Kawin",
  agamaPasangan: "",

  // Step 3 - Surat Permohonan
  suratPermohonan: "",

  // Step 4 - Unggah Dokumen
  fotokopiAktaKelahiran: null,
  fotokopiAktaPerkawinan: null,
  dokumenPerjalanRi: null,
  suratPjbtAsing: null,
  pasporAsing: null,
  buktiPengemPaspor: null,
  pasfoto: null,
};
