export const mapDetailToFormik = (data) => ({
  id_permohonan: data.id_permohonan || "",
  namaLengkapPemohon: data.nama_lengkap_pemohon || "",
  kewarganegaraanAsal: data.kewarganegaraan_asal_pemohon_text || "",
  tempatLahir: data.negara_lahir_pemohon_text || "",
  tanggalLahir: data.tgl_lahir_pemohon || "",
  jenisKelamin: data.jenis_kelamin_pemohon || "",
  agama: data.agama_pemohon || "",
  pekerjaan: data.pekerjaan_pemohon_text || "",

  statusPerkawinan: data.status_kawin || "",
  tanggalPernikahan: data.tgl_kawin || "",
  nomorAktaNikah: data.no_buku_nikah || "",
  nomorSkim: data.no_skim || "",
  statusAktivitas: data.status_aktivitas,

  provinsi: data.provinsi_pemohon_text || "",
  kabupaten: data.kab_kota_pemohon_text || "",
  kecamatan: data.kec_pemohon_text || "",
  kelurahan: data.desa_kel_pemohon_text || "",
  rt: data.rt || "",
  rw: data.rw || "",
  kodePos: data.kode_pos || "",
  alamatRumah: data.alamat_pemohon || "",
  nomorHp: data.no_telp_pemohon || "",
  email: data.email_pemohon || "",

  namaLenkapPasangan: data.nama_pasangan || "",
  nikPasangan: data.nik_pasangan || "",
  nomorHpPasangan: data.no_telp_pasangan || "",
  emailPasangan: data.email_pasangan || "",
  negaraLahirPasangan: data.negara_lahir_pasangan_text || "-",
  provinsiPasangan: data.provinsi_lahir_pasangan_text || "",
  kabupatenPasangan: data.kab_kota_lahir_pasangan_text || "",
  tanggalLahirPasangan: data.tgl_lahir_pasangan || "",
  pekerjaanPasangan: data.pekerjaan_pasangan_text || "",
  kewarganegaraanPasangan: data.kewarganegaraan_pasangan_text || "",
  jenisKelaminPasangan: data.jenis_kelamin_pasangan || "",
  agamaPasangan: data.agama_pasangan || "",
  files: data.files,
});
