export const NEXT_STEP = "stepper/NEXT_STEP";
export const PREV_STEP = "stepper/PREV_STEP";
export const RESET_STEPPER = "stepper/RESET_STEPPER";

export const SAVE_FORM_DATA = "SAVE_FORM_DATA";
export const SAVE_FORM_DATA_SUCCESS = "SAVE_FORM_DATA_SUCCESS";
export const SAVE_FORM_DATA_FAIL = "SAVE_FORM_DATA_FAIL";
export const RESET_FORM_DATA = "RESET_FORM_DATA";

export const SUBMIT_REGISTRATION_FORM = "SUBMIT_REGISTRATION_FORM";
export const SUBMIT_REGISTRATION_FORM_SUCCESS =
  "SUBMIT_REGISTRATION_FORM_SUCCESS";
export const SUBMIT_REGISTRATION_FORM_FAIL = "SUBMIT_REGISTRATION_FORM_FAIL";
