export const dataPelaporan = [
  {
    no: 1,
    tanggalPelaporan: "2025-07-01",
    jenisPelaporan: "Pendirian PT",
    namaPemberi: "Budi Santoso",
    nomorAkta: "01/Akta/2025",
    tanggalAkta: "2025-06-25",
    reportorium: "123/RPT/2025",
    jenisAkta: "Akta Pendirian",
    jenisWasiat: "Dalam Negeri",
  },
  {
    no: 2,
    tanggalPelaporan: "2025-07-02",
    jenisPelaporan: "Perubahan Direksi",
    namaPemberi: "Siti Aminah",
    nomorAkta: "02/Akta/2025",
    tanggalAkta: "2025-06-27",
    reportorium: "124/RPT/2025",
    jenisAkta: "Akta Perubahan",
    jenisWasiat: "Luar Negeri",
  },
  {
    no: 3,
    tanggalPelaporan: "2025-07-03",
    jenisPelaporan: "Pendirian CV",
    namaPemberi: "Ahmad Zulkarnain",
    nomorAkta: "03/Akta/2025",
    tanggalAkta: "2025-06-28",
    reportorium: "125/RPT/2025",
    jenisAkta: "Akta Pendirian",
    jenisWasiat: "Dalam Negeri",
  },
  {
    no: 4,
    tanggalPelaporan: "2025-07-04",
    jenisPelaporan: "Perubahan Anggaran Dasar",
    namaPemberi: "Maria Theresa",
    nomorAkta: "04/Akta/2025",
    tanggalAkta: "2025-06-29",
    reportorium: "126/RPT/2025",
    jenisAkta: "Akta Perubahan",
    jenisWasiat: "Luar Negeri",
  },
  {
    no: 5,
    tanggalPelaporan: "2025-07-05",
    jenisPelaporan: "Likuidasi",
    namaPemberi: "Jonathan Pratama",
    nomorAkta: "05/Akta/2025",
    tanggalAkta: "2025-06-30",
    reportorium: "127/RPT/2025",
    jenisAkta: "Akta Likuidasi",
    jenisWasiat: "Dalam Negeri",
  },
];

export const steps = [
  {
    id: 1,
    label: "Pembelian Voucher",
    description: `Voucher berhasil dibeli sebagai syarat awal pengajuan permohonan.`,
  },
  {
    id: 2,
    label: "Pendaftaran Permohonan",
    description: "Data permohonan telah diisi dan dikirim oleh pemohon.",
  },
  {
    id: 3,
    label: "SK Terbit",
    description:
      "Surat Keputusan (SK) telah diterbitkan dan siap diunduh oleh pemohon.",
    subDescription: "Cetak Surat Keputusan",
  },
];
