export const GET_PERMOHONAN_REQUEST = "GET_PERMOHONAN_REQUEST";
export const GET_PERMOHONAN_SUCCESS = "GET_PERMOHONAN_SUCCESS";
export const GET_PERMOHONAN_ERROR = "GET_PERMOHONAN_ERROR";

export const POST_PERMOHONAN_REQUEST = "POST_PERMOHONAN_REQUEST";
export const POST_PERMOHONAN_SUCCESS = "POST_PERMOHONAN_SUCCESS";
export const POST_PERMOHONAN_ERROR = "POST_PERMOHONAN_ERROR";
export const SET_PERMOHONAN = "SET_PERMOHONAN";

export const DRAFT_REQUEST = "DRAFT_REQUEST";
export const DRAFT_SUCCESS = "DRAFT_SUCCESS";
export const DRAFT_ERROR = "DRAFT_ERROR";

export const NEXT_STEP_REQUEST = "NEXT_STEP_REQUEST";
export const NEXT_STEP_SUCCESS = "NEXT_STEP_SUCCESS";
export const NEXT_STEP_ERROR = "NEXT_STEP_ERROR";

// SUBMIT FINAL
export const SUBMIT_FORM_REQUEST = "SUBMIT_FORM_REQUEST";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_ERROR = "SUBMIT_FORM_ERROR";
