export const API_ERROR_USMAN = "API_ERROR";

export const GET_DROPDOWN_LIST_ROLE = "GET_DROPDOWN_LIST_ROLE";
export const GET_DROPDOWN_LIST_ROLE_SUCCESS = "GET_DROPDOWN_LIST_ROLE_SUCCESS";

export const GET_DROPDOWN_LIST_MODULES = "GET_DROPDOWN_LIST_MODULES";
export const GET_DROPDOWN_LIST_MODULES_SUCCESS = "GET_DROPDOWN_LIST_MODULES_SUCCESS";

export const GET_LIST_PENGGUNA = "GET_LIST_PENGGUNA";
export const GET_LIST_PENGGUNA_SUCCESS = "GET_LIST_PENGGUNA_SUCCESS";

export const GET_DETAIL_PENGGUNA = "GET_DETAIL_PENGGUNA";
export const GET_DETAIL_PENGGUNA_SUCCESS = "GET_DETAIL_PENGGUNA_SUCCESS";

export const GET_DATA_LOG = "GET_DATA_LOG";
export const GET_DATA_LOG_SUCCESS = "GET_DATA_LOG_SUCCESS";

export const GET_ACTIVE_USER = "GET_ACTIVE_USER";
export const GET_ACTIVE_USER_SUCCESS = "GET_ACTIVE_USER_SUCCESS";