export const dataVerifikasi = [
  {
    no: 1,
    noRekomendasi: "REK-001/2025",
    namaLengkap: "Ahmad Fauzi",
    emailPemohon: "ahmad.fauzi@example.com",
    tanggalLahir: "1990-05-12",
    negaraAsal: "Indonesia",
    verifikasi: [1, 2, 3, 4],
  },
  {
    no: 2,
    noRekomendasi: "REK-002/2025",
    namaLengkap: "Maria Lopez",
    emailPemohon: "maria.lopez@example.com",
    tanggalLahir: "1985-08-24",
    negaraAsal: "Meksiko",
    verifikasi: [1, 2, 3, 4],
  },
  {
    no: 3,
    noRekomendasi: "REK-003/2025",
    namaLengkap: "John Smith",
    emailPemohon: "john.smith@example.com",
    tanggalLahir: "1992-11-03",
    negaraAsal: "Amerika Serikat",
    verifikasi: [1, 2, 3, 4],
  },
  {
    no: 4,
    noRekomendasi: "REK-004/2025",
    namaLengkap: "Siti Nurhaliza",
    emailPemohon: "siti.nurhaliza@example.com",
    tanggalLahir: "1989-04-17",
    negaraAsal: "Malaysia",
    verifikasi: [1, 2, 3, 4],
  },
  {
    no: 5,
    noRekomendasi: "REK-005/2025",
    namaLengkap: "Hiroshi Tanaka",
    emailPemohon: "hiroshi.tanaka@example.com",
    tanggalLahir: "1995-01-30",
    negaraAsal: "Jepang",
    verifikasi: [1, 2, 3, 4],
  },
];
